# jscpd:ignore-start
# See https://json.schemastore.org/github-workflow.json for vocabulary and rules
name: CI

on:
  push:

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_SQLFLUFF: false

# jscpd:ignore-end
